# Generated by Django 5.1.5 on 2025-01-17 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role',
        ),
    ]
