# Generated by Django 5.1.5 on 2025-01-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_role_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(default='', max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
